services:
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:3.13.2
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock:ro

  android:
    container_name: android
    depends_on:
      - wiremock
    image: budtmo/docker-android:emulator_12.0_v3.1.1-p0
    ports:
      - "6080:6080"
      - "4723:4723"

    environment:
      - WEB_VNC=true
      - APPIUM=true
      - EMULATOR_ARGS=-no-snapshot -wipe-data -no-audio -no-boot-anim

    volumes:
      - ./wiremock:/home/wiremock

    devices:
      - "/dev/kvm"